[book]
authors = ["Paradise Station"]
language = "en"
multilingual = false
src = "docs"
title = "Paradise Station Development"

[output.html]
theme = "./docs/theme"
additional-css = ["./docs/css/para.css"]
additional-js = ["./docs/js/highlight-dm.js"]
default-theme = "navy"
preferred-dark-theme = "navy"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
