[book]
authors = ["warriorstar-orion"]
language = "en"
multilingual = false
src = "src"
title = "Paradise Station Development"

[output.html]
additional-css = [
	"./src/css/general.css",
	"./src/css/variables.css",
	"./src/css/custom.css",
]
default-theme = "navy"
preferred-dark-theme = "navy"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
